version: '3'

services:
  symetria_emotions:
    build: .
    container_name: symetria_emotions
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./:/app
    expose:
      - 5000
    environment:
      VIRTUAL_HOST: onism.chad-partners.com
      LETSENCRYPT_HOST: onism.chad-partners.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
